### ISSUE TITLE
Screen recording not working 

### ISSUE THREAD

**Issue by Aanu1995** [Isvisoft/flutter_screen_recording#12] opened 2020-03-20 16:06 UTC
I am using Flutter  v1.12.13+hotfix.8 (stable channel) and Android SDK version 29.0.3 . The play button is not doing anything and there is no error in the console.

**Comment by salime45** [comment] 2020-03-24 08:21
Hi, 

Are you using the repo or the pub package? 

Have you try in different devices?

**Comment by grigvik** [comment] 2020-03-25 16:15
Hi
Yes, the plugin doesn’t work. When I press the play button 
await FlutterScreenRecording.startRecordScreen("Title");
returns false. And there is no error on the console.

**Comment by Aanu1995** [comment] 2020-03-25 16:29
@salime45 I tried using the pub package

**Comment by DmitriyIgnashchenko** [comment] 2020-03-25 17:09
> Hi
> Yes, the plugin doesn’t work. When I press the play button
> await FlutterScreenRecording.startRecordScreen("Title");
> returns false. And there is no error on the console.
> I used the pub package and tested on virtual devices and on my android phone.

having the same issue

**Comment by DmitriyIgnashchenko** [comment] 2020-03-25 18:00
hope you'll fix it

**Comment by salime45** [comment] 2020-03-26 16:44
Can you provide a project with the fail?

**Comment by DmitriyIgnashchenko** [comment] 2020-03-26 17:13
> Can you provide a project with the fail?

here you are

https://github.com/DmitriyIgnashchenko/record_screen_test

**Comment by DmitriyIgnashchenko** [comment] 2020-03-26 17:34
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale ru-RU)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.43.2)

**Comment by prashantspandey** [comment] 2020-04-01 12:29
HI any updates ! My recorder is also not working even after the permissions. the start variable is always false. Please fix this.

**Comment by salime45** [comment] 2020-04-04 18:10
Right now, we not have time to resolve this, for us the plugin works.

I recomend you fork the plugin and debug .

**Comment by prashantspandey** [comment] 2020-04-28 03:11
Has this been fixed yet?

**Comment by salime45** [comment] 2020-04-28 10:44
Seems @handofthecode fix the problems. You can try his report meanwhile test the changes and merge.
https://github.com/handofthecode/flutter_screen_recording

**Comment by JAYTARPARA** [comment] 2020-05-07 05:39
> Right now, we not have time to resolve this, for us the plugin works.
> 
> I recomend you fork the plugin and debug .

What a reply man. **HATS OFF TO YOU. FROM WHERE YOU GOT THE TIME TO DEVELOP IT??**

**Comment by JAYTARPARA** [comment] 2020-05-07 05:43
> Seems @handofthecode fixed the problems. You can try this repository meanwhile we test the changes and merge.
> https://github.com/handofthecode/flutter_screen_recording

Also for your kind information. This is also not working. Same issue is there still.

**Comment by startupgurukul** [comment] 2020-05-09 01:01
Dear @JAYTARPARA. Be nice, instead of being thankful for sharing their work,  you expect them to debug issues which they are saying they have no bandwidth to look at. 

If you have the skillset to resolve it, pls do and send a pull request instead of having a shouting match.

**Comment by JAYTARPARA** [comment] 2020-05-09 01:04
@startupgurukul This is the scenario When client is on your head and asking to do it ASAP and use the plugin instead of core functionality.

**Comment by aryan29** [comment] 2020-05-14 11:36
Yes for me also it is not working

**Comment by salime45** [comment] 2020-05-14 16:45
I did a little update to fix some bugs. Even so in what devices is failing the app?

**Comment by Aanu1995** [comment] 2020-05-14 16:56
@salime45 Precisely... The issue is with Android

**Comment by salime45** [comment] 2020-05-14 17:02
Yeah, but what device are you using?

**Comment by Aanu1995** [comment] 2020-05-14 17:08
Tecno and Samsung

**Comment by salime45** [comment] 2020-05-14 17:10
You can execute the example in the repository and paste the log?

**Comment by safdher** [comment] 2020-05-19 00:40
I have the same problem. When i use your repo it works. but I use the same code in mine it not work..

**Comment by salime45** [comment] 2020-05-19 07:04
> I have the same problem. When i use your repo it works. but I use the same code in mine it not work..

Can you paste your pubspec.yaml? And tell us what device are you using?

**Comment by safdher** [comment] 2020-05-19 15:34
This is My Yaml file...


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  video_player: ^0.10.11
  flutter_screen_recording: ^1.0.5
  quiver: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  permission_handler: ^4.1.0
  open_file: ^3.0.1


flutter:
  assets:
    - data/
    - images/Back.mp4
 
These Permission Are put in XML file
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
          <uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />
          <uses-permission android:name="android.permission.RECORD_AUDIO" />


Your Code is run perfectly in my Mobile.. So I think Mobile is not depending on this error( Vivo 1906 is my model)

**Comment by salime45** [comment] 2020-05-19 15:58
Can you try this way ?

  flutter_screen_recording:
    git:
      url: https://github.com/isvisoft/flutter_screen_recording.git

**Comment by safdher** [comment] 2020-05-23 03:39
Sorry for the late replay,

I just put the same code in yaml file but my code doesn't work. after that I copy my code to your project then it work. i don't know why it works.. But get the result. Thanks for your support..

**Comment by salime45** [comment] 2020-05-25 09:27
that is strange if you want you can send me a copy of the code

**Comment by safdher** [comment] 2020-05-26 02:25
https://github.com/safdher/Dictionary.git

this is my code,

**Comment by salime45** [comment] 2020-05-26 08:01
Thanks @safdher. I think is fixed now. Can you try?

Be sure to upgrade the git package, sometimes not refresh well

**Comment by gotirahul96** [comment] 2020-05-27 06:31
It is working for me but the problem is how to record the audio as well because it is only recording the audio without the audio..Please can anyone help ? Thankyou

**Comment by salime45** [comment] 2020-05-27 07:03
> It is working for me but the problem is how to record the audio as well because it is only recording the audio without the audio..Please can anyone help ? Thankyou

This plugin is not prepare to record the audio.  I close the thread because there a different issues not related . If anyone have any problem open new issue please. 

Thanks

**Closed by salime45** 2020-05-27 07:03 UTC

**Comment by gotirahul96** [comment] 2020-05-27 07:11
> > It is working for me but the problem is how to record the audio as well because it is only recording the audio without the audio..Please can anyone help ? Thankyou
> 
> This plugin is not prepare to record the audio. I close the thread because there a different issues not related . If anyone have any problem open new issue please.
> 
> Thanks

So if it is not prepared to record audio why it is asking to add permission ?
![image](https://user-images.githubusercontent.com/46042402/82988807-593bba80-a017-11ea-9251-6ff7cf013dab.png)

**Comment by salime45** [comment] 2020-05-27 07:50
The library for screen recording in android recommended add the permission

**Comment by gotirahul96** [comment] 2020-05-27 08:06
Can you add the audio feature in this library ? As it is the requirement
for the client. THANKYOU in advance.

**Comment by salime45** [comment] 2020-05-27 08:09
We have not plans for this feature. You can create a new issue and tag like feature. We will study in  the future
