### ISSUE TITLE
Deprecated Version Issue

### ISSUE THREAD

**Issue by aKaushik941** [Isvisoft/flutter_screen_recording#106] opened 2024-02-20 08:11 UTC
The plugin `flutter_screen_recording` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by acastry** [comment] 2024-03-13 03:58
Any news from here ? I am afraid of using this plugin and encountering issues lately.

**Comment by TNorbury** [comment] 2024-05-29 04:45
This is a duplicate of #101. I'm actively working on the issue, see my comment in that thread

**Comment by TNorbury** [comment] 2024-05-29 17:51
PR is open. See the PR description for instructions on how to use my branch in your project

**Closed** 2024-06-01 08:10 UTC
